app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/

Route::resource('/', 'HomeController');
Route::controller('/manga/{slug}/{chapter?}/{page?}', 'MangaController');
Route::controller('/directory', 'DirectoryController');
Route::controller('/profile/{slug}', 'ProfileController');

Route::controller('/ajax', 'AjaxController');
Route::controller('/cron', 'CronController');

Route::get('auth/facebook', 'Auth\AuthController@redirectToProvider');
Route::get('auth/facebook/callback', 'Auth\AuthController@handleProviderCallback');
Route::get('/logout', function(){
	Auth::logout();	
	return redirect('/');
});


// Route::controller('/manga/{slug}/{chapter?}/{page?}', 'MangaController');
Route::controller('/search', 'SearchController');

Route::group(['middleware' => 'ManggakuUnity\Http\Middleware\AdminMiddleware','prefix' => 'prabu'], function()
{
    Route::resource('/overview', 'IndexAdminController');
    Route::resource('/user', 'UserAdminController');
    Route::resource('/manga', 'MangaAdminController');
    Route::resource('/chapter', 'ChapterAdminController');
    Route::post('/chapterbatch', 'ChapterAdminController@batchUploadHandler');
    Route::resource('/creator', 'CreatorAdminController');
    Route::controller('/publish', 'PublishAdminController');
    Route::resource('/redirect/{notificationID?}/', 'UltilityAdminController@redirect');
    // Route::resource('mn-admin/genre', 'GenreAdminController');
    // Route::resource('mn-admin/type', 'TypeAdminController');
    // Route::resource('mn-admin/status', 'StatusAdminController');
    // Route::resource('mn-admin/scrapper', 'ScrapperAdminController');
});

Route::get('distro', 'PageController@distro');
Route::get('partners', 'PageController@partners');
Route::get('faq', 'PageController@faq');
Route::get('join', 'PageController@join');
Route::resource('sitemap', 'SitemapController');

app/Http/Controllers/CronController.php
<?php

namespace ManggakuUnity\Http\Controllers;

use Illuminate\Http\Request;
use ManggakuUnity\Http\Requests;
use ManggakuUnity\Http\Controllers\Controller;
use ManggakuUnity\Http\CustomClass\MAutoupdate;

use Storage;
use Carbon;

use ManggakuUnity\Meta;
use ManggakuUnity\Chapter;
use ManggakuUnity\GrabList;
use ManggakuUnity\Scrapper;

class CronController extends Controller
{
    public function getIndex()
    {
        $now                =   Carbon::now()->timestamp;
        $updatelists        =   Scrapper::where('active','=','1');
        $updatelists->where('nextCheck','<',$now);
        $updatelists->orderBy('lastCheck','ASC');
        if ($updatelists->count()>0) {
            $updatelist = $updatelists->first();
            
                $manga      = $updatelist->manga;
                $chapter    = $manga->getLastChapter() + 1;                
                $update     = new MAutoupdate($manga->id, $chapter);
                $result     = $update->execute();
                if ($result['status']) {
                    $chapterNew = new Chapter;
                    $chapterNew->chapter   = $chapter;
                    $chapterNew->id_manga  = $manga->id;
                    $chapterNew->save();
                    exit;
                }
            
        }
    }

    public function getUploads3()
    {
    	$rootMangaDirectory = config('app.manga_local_path');

        $mangaDirectoryLists = scandir($rootMangaDirectory);
        $mangaDirectoryLists = array_diff($mangaDirectoryLists, array('.', '..','.DS_Store'));
        
        /*Get First Folder*/
        foreach ($mangaDirectoryLists as $key => $directory) {
            $chapterDirectory           =   $rootMangaDirectory."/".$directory;
            $chapterDirectoryLists      =   array_diff(scandir($chapterDirectory), array('.', '..','.DS_Store'));
            foreach ($chapterDirectoryLists as $key => $chapter) {
                $fileDirectory          = $chapterDirectory."/".$chapter;
                $fileDirectoryLists     =   array_diff(scandir($fileDirectory), array('.', '..','.DS_Store'));

                /*Time To Upload It*/
                foreach ($fileDirectoryLists as $key => $file) {
                    $onlinePath = 'mangas/'.$directory.'/'.$chapter."/".$file;
                    Storage::put($onlinePath, file_get_contents($fileDirectory.'/'.$file));
                    unlink($fileDirectory.'/'.$file);
                }
                
                rmdir($fileDirectory);
            }
            rmdir($chapterDirectory);
            exit;
        }
    }
}

resources/views/admin/_footer.blade.php
</div>
 
</div>
 
<a class="exit-offscreen"></a>
</section>
 
</section>
</div>
<script src="/js/jquery.js"></script>
<script src="/js/admin.js"></script>
 
</body>
 
</html>

resources/views/admin/_header.blade.php
<!doctype html>
<html class="no-js" lang="">
	<head>
 
	<meta charset="utf-8">
	<meta name="description" content="Flat, Clean, Responsive, application admin template built with bootstrap 3">
	<meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1, maximum-scale=1">
 
	<title>Manggaku - Admin Dashboard</title> 
	<link rel="stylesheet" href="/css/admin.css">
 
	<!--[if lt IE 9]>
	        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
	        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
	    <![endif]-->
</head>
 
<body>
	<div class="app">
	<header class="header header-fixed navbar">
	<div class="brand"> 
		<a href="javascript:;" class="ti-menu off-left visible-xs" data-toggle="offscreen" data-move="ltr"></a>
		<a href="/prabu" class="navbar-brand">
			<img src="/img/logo.png" alt="">
			<span class="heading-font">
				Manggaku
			</span>
		</a>

	</div>
	<ul class="nav navbar-nav">
		<li class="hidden-xs">

			<a href="javascript:;" class="toggle-sidebar">
				<i class="ti-menu"></i>
			</a>

		</li>
		<li class="header-search">

			<a href="javascript:;" class="toggle-search">
				<i class="ti-search"></i>
			</a>

			<div class="search-container">
				<form role="search">
					<input type="text" class="form-control search" placeholder="type and press enter">
				</form>
			</div>
		</li>
	</ul>
	<ul class="nav navbar-nav navbar-right">
		<li class="dropdown hidden-xs">
			<a href="javascript:;" data-toggle="dropdown">
				<i class="ti-more-alt"></i>
			</a>
			<ul class="dropdown-menu animated zoomIn">
				<li class="dropdown-header">Quick Links</li>
				<li>
					<a href="javascript:;">Start New Campaign</a>
				</li>
				<li>
					<a href="javascript:;">Review Campaigns</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="javascript:;">Settings</a>
				</li>
				<li>
					<a href="javascript:;">Wish List</a>
				</li>
				<li>
					<a href="javascript:;">Purchases History</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="javascript:;">Activity Log</a>
				</li>
				<li>
					<a href="javascript:;">Settings</a>
				</li>
				<li>
					<a href="javascript:;">System Reports</a>
				</li>
				<li class="divider"></li>
				<li>
					<a href="javascript:;">Help</a>
				</li>
				<li>
					<a href="javascript:;">Report a Problem</a>
				</li>
			</ul>
		</li>
		<li class="notifications dropdown">
			<a href="javascript:;" data-toggle="dropdown">
				<i class="ti-bell"></i>
				@if(Auth::user()->notification()->unreaded()->count()>0)
				<div class="badge badge-top bg-danger animated flash">
					<span>{{Auth::user()->notification()->unreaded()->count()}}</span>
				</div>
				@endif
			</a>
			<div class="dropdown-menu animated fadeInLeft">
				<div class="panel panel-default no-m">
					<div class="panel-heading small"><b>Notifications</b>
					</div>
					<ul class="list-group">
						@foreach(Auth::user()->notification()->unreaded()->take(10)->get() as $notification)
							{!!$notification->parseForAdmin()!!}
						@endforeach
						<!-- <li class="list-group-item">
							<a href="javascript:;">
								<div class="pull-left mt5 mr15">
									<div class="circle-icon bg-danger">
										<i class="ti-download"></i>
									</div>
								</div>
								<div class="m-body">
									<span>Upload Progress</span>
									<div class="progress progress-xs mt5 mb5">
										<div class="progress-bar" role="progressbar" aria-valuenow="40" aria-valuemin="0" aria-valuemax="100" style="width: 40%">
										</div>
									</div>
									<span class="time small">Submited 23 mins ago</span>
								</div>
							</a>
						</li>
						<li class="list-group-item">
							<a href="javascript:;">
								<span class="pull-left mt5 mr15">
									<img src="img/face3.jpg" class="avatar avatar-sm img-circle" alt="">
								</span>
								<div class="m-body">
									<em>Status Update:</em>
									<span>All servers now online</span>
									<span class="time small">5 days ago</span>
								</div>
							</a>
						</li> -->
					</ul>
					<div class="panel-footer">
						<a href="javascript:;">See all notifications</a>
					</div>
				</div>
			</div>
		</li>
		<li class="off-right">
			<a href="javascript:;" data-toggle="dropdown">
				<img src="/img/avatar.jpg" class="header-avatar img-circle" alt="user" title="user">
				<span class="hidden-xs ml10">Franky Soputra</span>
				<i class="ti-angle-down ti-caret hidden-xs"></i>
			</a>
			<ul class="dropdown-menu animated fadeInRight">
				<li>
					<a href="javascript:;">Settings</a>
				</li>
				<li>
					<a href="javascript:;">Upgrade</a>
				</li>
				<li>
					<a href="javascript:;">
						<div class="badge bg-danger pull-right">3</div>
						<span>Notifications</span>
					</a>
				</li>
				<li>
					<a href="javascript:;">Help</a>
				</li>
				<li>
					<a href="/logout">Logout</a>
				</li>
			</ul>
		</li>
	</ul>
</header>

<section class="layout">

	<aside class="sidebar offscreen-left">

		<nav class="main-navigation" data-height="auto" data-size="6px" data-distance="0" data-rail-visible="true" data-wheel-step="10">
			<p class="nav-title">MENU</p>
			<ul class="nav">
				<li>
					<a href="{{route('prabu.overview.index')}}">
						<i class="ti-home"></i>
						<span>Dashboard</span>
					</a>
				</li>
				
				<li>
					<a href="{{route('prabu.user.index')}}">
						<i class="ti-user"></i>
						<span>User</span>
					</a>
				</li>

				<!-- <li>
					<a href="javascript:;">
						<i class="toggle-accordion"></i>
						<i class="ti-window"></i>
						<span>Interface</span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="">
								<span>Slider</span>
							</a>
						</li>
					</ul>
				</li> -->

				<li>
					<a href="javascript:;">
						<i class="toggle-accordion"></i>
						<i class="ti-folder"></i>
						<span>Manga</span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="{{route('prabu.manga.index')}}">
								<span>Manga</span>
							</a>
						</li>
						<li>
							<a href="{{route('prabu.creator.index')}}">
								<span>Creator</span>
							</a>
						</li>
						<li>
							<a href="">
								<span>Genre</span>
							</a>
						</li>
						<li>
							<a href="">
								<span>Tipe</span>
							</a>
						</li>
						<li>
							<a href="">
								<span>Status</span>
							</a>
						</li>
					</ul>
				</li>

				<li>
					<a href="javascript:;">
						<i class="toggle-accordion"></i>
						<i class="ti-basketball"></i>
						<span>Lainnya</span>
					</a>
					<ul class="sub-menu">
						<li>
							<a href="">
								<span>Cron Job</span>
							</a>
						</li>
					</ul>
				</li>
			</ul>
		</nav>
	</aside>


	<section class="main-content">

		<div class="content-wrap">

			<div class="wrapper">

resources/views/admin/chapterShow.blade.php
@include('admin._header')
	<div class="row">
		<div class="col-md-4">
			{!!Form::open(array('route'=>['prabu.chapter.update',$chapter->id],'method'=>'PUT','files' => true))!!}
			<div class="panel panel-default">
				<div class="panel-heading">
					Chapter Detail
				</div>
				<div class="panel-body">
					<div class="form-group">
						<label class="control-label">Chapter</label>
							{!!Form::input('text', 'chapter', $chapter->chapter, ['class' => 'form-control'])!!}
						
					</div>
					<div class="form-group">
						<label class="control-label">Name</label>
							{!!Form::input('text', 'name', $chapter->name, ['class' => 'form-control'])!!}
						
					</div>
					<hr>
					<div class="form-group">
						<label class="control-label">Manga File</label>
							<input type="file" name="file[]" multiple>
						
					</div>
					<div class="form-group">
						<label class="control-label">URL Scrap</label>
							{!!Form::input('text', 'url', null, ['class' => 'form-control'])!!}
							<small>Scrap From Single Page <span class="text-danger">Please Leave Manga File Empty</span></small>
						
					</div>
					<div class="form-group">
						<label class="control-label">Manga Directory</label>
							{!!Form::input('text', 'directory', null, ['class' => 'form-control','disabled'])!!}
							<input type="checkbox" name="fromDirectory" value="1"> Scrap From Manga Directory
						
					</div>
					<hr>
					<div class="form-group">
 						<input type="checkbox" name="deleteOldFile" value="1"> Hapus File Lama
 					</div>
				</div>
				<div class="panel-footer">
					<input type="submit" name="submit" value="Simpan Perubahan" class="btn btn-success btn-block">
				</div>
			</div>
			</form>
		
			<form action="/prabu/publish/setimage" method="POST">
			<div class="panel panel-default">
				<div class="panel-heading">
					Publish To Social Media
				</div>
				<div class="panel-body">
					<div class="form-group">
						<input type="hidden" name="id_manga" value="{{$chapter->manga->id}}">
						<input type="hidden" name="id_chapter" value="{{$chapter->id}}">
						<label>Pilih Image Index yang ingin di publish</label>
						<select name="imageToPublish" id="" class="form-control">
							@foreach($mangaLists as $key => $mangaList)
								<option value="{{config('app.manga_remote_url')."/".$mangaList}}">Index {{$key}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="panel-footer">
					<input type="submit" name="submit" value="Publish" class="btn btn-success btn-block">
				</div>
			</div>
			</form>
			<div class="panel panel-default">
				<div class="panel-body">
					{!!Form::open(array('route'=>['prabu.chapter.destroy',$chapter->id],'method'=>'DELETE'))!!}
						<input type="submit" name="submit" value="Hapus Chapter" class="btn btn-danger btn-block">
					</form>
				</div>	
			</div>
		</div>
		<div class="col-md-8">
			<div class="row">
				@foreach($mangaLists as $key => $mangaList)
					<div class="col-md-4 mb30">
						<img src="{{config('app.manga_remote_url')."/".$mangaList}}" alt="" width="100%" height="300px;" style="height:300px !important;">
						<div class="alert alert-danger">
							Index - {{$key}}
						</div>
					</div>
				@endforeach
			</div>
		</div>
	</div>
@include('admin._footer')

resources/views/admin/creatorCreate.blade.php
@include('admin._header')
	<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<section class="panel">
			<header class="panel-heading">Create Creator</header>
			{!!Form::open(array('route'=>'prabu.creator.store','files' => true,'class'=>'form-horizontal'))!!}
			<div class="panel-body">
				@if (count($errors) > 0)
				    <div class="alert alert-danger">
				            @foreach ($errors->all() as $error)
				                {{ $error }}<br>
				            @endforeach
				    </div>
				@endif
				<div class="form-group">
					<label class="col-sm-2 control-label">Name</label>
					<div class="col-sm-10">
						{!!Form::input('text', 'name', null, ['class' => 'form-control'])!!}
					</div>
				</div>
			</div>
			<div class="panel-footer text-right">
				<input type="submit" class="btn btn-primary" value="Simpan" />
			</div>
			</form>
		</section>
	</div>
</div>
@include('admin._footer')

resources/views/admin/creatorIndex.blade.php
@include('admin._header')
	<section class="panel">
		<header class="panel-heading">Creators Lists</header>
		<div class="panel-body">
			<div class="row mb20">
				<div class="col-md-4">
					<a href="/prabu/creator/create" class="btn btn-primary"><span class="ti-plus"></span> Create Creator</a>
				</div>
				<div class="col-md-8 text-right">
					<form class="form-inline" role="form">
						<div class="form-group mr5">
							<input type="email" class="form-control" id="exampleInputEmail2" placeholder="Search">
						</div>

						<button type="submit" class="btn btn-default">Search</button>
					</form>
				</div>
			</div>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Name</th>
						<th width="5%"></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Name</th>
						<th width="5%"></th>
					</tr>
				</tfoot>
				<tbody>
					@foreach($creators as $creator)
					<tr>
						<td>{{$creator->name}}</td>
						<td><a href="{{route('prabu.creator.show',$creator->id)}}" class="btn btn-sm btn-default">Lihat creator</a></td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		<div class="panel-footer">
			{!! $creators->render() !!}
		</div>
	</section>
@include('admin._footer')

resources/views/admin/mangaCreate.blade.php
@include('admin._header')
	<div class="row">
	<div class="col-md-8 col-md-offset-2">
		<section class="panel">
			<header class="panel-heading">Create Manga</header>
			{!!Form::open(array('route'=>'prabu.manga.store','files' => true,'class'=>'form-horizontal'))!!}
			<div class="panel-body">
				@if (count($errors) > 0)
				    <div class="alert alert-danger">
				            @foreach ($errors->all() as $error)
				                {{ $error }}<br>
				            @endforeach
				    </div>
				@endif
				<div class="form-group">
					<label class="col-sm-2 control-label">Name</label>
					<div class="col-sm-10">
						{!!Form::input('text', 'name', null, ['class' => 'form-control'])!!}
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Alt Name</label>
					<div class="col-sm-10">
						{!! Form::textarea('alt_name', null, ['class' => 'form-control','size' => '30x3']) !!}
						<p class="help-block">Satu Nama Setiap Baris</p>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Author</label>
					<div class="col-sm-10">
						<select class="form-control chosen" name="author">
							@foreach($creators->get() as $creator)
								<option value="{{$creator->id}}">{{$creator->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Artist</label>
					<div class="col-sm-10">
						<select class="form-control chosen" name="artist">
							@foreach($creators->get() as $creator)
								<option value="{{$creator->id}}">{{$creator->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Released</label>
					<div class="col-sm-10">
						{!!Form::input('text', 'released', null, ['class' => 'form-control'])!!}
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Plot</label>
					<div class="col-sm-10">
						{!! Form::textarea('plot', null, ['class' => 'form-control','size' => '30x3']) !!}
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Type</label>
					<div class="col-sm-10">
						<select class="form-control chosen" name="type">
							@foreach($types->get() as $type)
								<option value="{{$type->id}}">{{$type->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Genre</label>
					<div class="col-sm-10">
						<select class="form-control chosen" multiple name="genre[]" data-placeholder="ketikkan Genre">
							@foreach($genres->get() as $genre)
								<option value="{{$genre->id}}">{{$genre->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Status</label>
					<div class="col-sm-10">
						<select class="form-control chosen" name="status">
							@foreach($statuses->get() as $status)
								<option value="{{$status->id}}">{{$status->name}}</option>
							@endforeach
						</select>
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Cover URL</label>
					<div class="col-sm-10">
						{!!Form::input('text', 'coverURL', null, ['class' => 'form-control'])!!}
					</div>
				</div>
				<div class="form-group">
					<label class="col-sm-2 control-label">Cover</label>
					<div class="col-sm-10">
						<input type="file" name="cover">
					</div>
				</div>
			</div>
			<div class="panel-footer text-right">
				<input type="submit" class="btn btn-primary" value="Simpan" />
			</div>
			</form>
		</section>
	</div>
</div>
@include('admin._footer')

resources/views/admin/mangaIndex.blade.php
@include('admin._header')
	<section class="panel">
		<header class="panel-heading">Mangas Lists</header>
		<div class="panel-body">
			<div class="row mb20">
				<div class="col-md-4">
					<a href="/prabu/manga/create" class="btn btn-primary"><span class="ti-plus"></span> Create Manga</a>
				</div>
				<div class="col-md-8 text-right">
					<form class="form-inline" role="form" method="get">
						<div class="form-group mr5">
							<input type="text" name="q" class="form-control" placeholder="Search" value="{{$q}}">
						</div>

						<button type="submit" class="btn btn-default">Search</button>
					</form>
				</div>
			</div>
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Title</th>
						<th>Author</th>
						<th>Artist</th>
						<th>Released</th>
						<th>Rating</th>
						<th>Created At</th>
						<th width="5%"></th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Title</th>
						<th>Author</th>
						<th>Artist</th>
						<th>Released</th>
						<th>Rating</th>
						<th>Created At</th>
						<th width="5%"></th>
					</tr>
				</tfoot>
				<tbody>
					@foreach($mangas as $manga)
					<tr>
						<td>{{$manga->name}}</td>
						<td>{{$manga->getAuthor['name']}}</td>
						<td>{{$manga->getArtist['name']}}</td>
						<td>{{$manga->released}}</td>
						<td>{{$manga->rate}}</td>
						<td>{{$manga->created_at}}</td>
						<td><a href="{{route('prabu.manga.show',$manga->id)}}" class="btn btn-sm btn-default">Lihat Manga</a></td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		<div class="panel-footer">
			{!! $mangas->render() !!}
		</div>
	</section>
@include('admin._footer')

resources/views/admin/overview.blade.php
@include('admin._header')
	<div class="row">
		<div class="col-md-6">
			{!!Form::open(array('route'=>['prabu.overview.update',$manga->id],'method'=>'PUT','files' => true))!!}
			<div class="panel panel-default">
				<div class="panel-heading">
					Reset Manga Cover
				</div>
				<div class="panel-body">
					<div class="form-group">
						<div class="col-md-12">
							<h4>Manga : {{$manga->name}}</h4>
						</div>
					</div>
					<div class="form-group">
						<label class="col-sm-2 control-label">Cover URL</label>
						<div class="col-sm-10">
							{!!Form::input('text', 'coverURL', null, ['class' => 'form-control'])!!}
						</div>
					</div>
				</div>
				<div class="panel-footer">
					<input type="submit" value="Submit" class="btn btn-primary">
				</div>
			</div>
		</form>
		</div>
	</div>
@include('admin._footer')

resources/views/admin/publishCrop.blade.php
@include('admin._header')
	<form action="" method="POST">
		<div class="row">
			<div class="col-md-4">
				<div class="form-group">
					<label>TextAutopost</label>
					<textarea name="autopost" id="" cols="30" rows="5" class="form-control">{{$template}}</textarea>
				</div>
				<div class="form-group">
					<input type="submit" class="btn btn-success" value="Publish Ke Social Media">
				</div>
				<input type="hidden" id="x1" name="x1">
				<input type="hidden" id="y1" name="y1">
				<input type="hidden" id="x2" name="x2">
				<input type="hidden" id="y2" name="y2">
				<input type="hidden" id="w" name="w">
				<input type="hidden" id="h" name="h">
				<input type="hidden" name="image" value="{{$url}}">
			</div>
			<div class="col-md-8">
				<img src="{{$url}}" alt="" class="cropimage">
			</div>
		</div>
	</form>
@include('admin._footer')

resources/views/admin/userIndex.blade.php
@include('admin._header')
	<section class="panel">
		<header class="panel-heading">User Lists</header>
		<div class="panel-body">
			<!-- <div class="row mb20">
				<div class="col-md-4">
					<a href="/prabu/creator/create" class="btn btn-primary"><span class="ti-plus"></span> Create Creator</a>
				</div>
				<div class="col-md-8 text-right">
					<form class="form-inline" role="form">
						<div class="form-group mr5">
							<input type="email" class="form-control" id="exampleInputEmail2" placeholder="Search">
						</div>

						<button type="submit" class="btn btn-default">Search</button>
					</form>
				</div>
			</div> -->
			<table class="table table-bordered table-striped">
				<thead>
					<tr>
						<th>Name</th>
						<th width="20%"> Created At</th>
					</tr>
				</thead>
				<tfoot>
					<tr>
						<th>Name</th>
						<th width="20%"> Created At</th>
					</tr>
				</tfoot>
				<tbody>
					@foreach($users as $user)
					<tr>
						<td>{{$user->name}}</td>
						<td>{{humanDate($user->created_at)}}</td>
					</tr>
					@endforeach
				</tbody>
			</table>
		</div>
		<div class="panel-footer">
			{!! $users->render() !!}
		</div>
	</section>
@include('admin._footer')